#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import shutil


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate adapter instruction shims from canonical AGENTS.md.")
    parser.add_argument("--agent-root", default=str(Path.home() / ".agents"))
    parser.add_argument("--codex-agents-path", default=str(Path.home() / ".codex" / "AGENTS.md"))
    parser.add_argument("--claude-path", default=str(Path.home() / ".claude" / "CLAUDE.md"))
    parser.add_argument(
        "--opencode-human-path",
        default=str(Path.home() / ".config" / "opencode" / "memory" / "human.md"),
    )
    parser.add_argument("--what-if", action="store_true")
    return parser.parse_args()


def backup_if_changed(path: Path, new_content: str, what_if: bool) -> None:
    if not path.exists():
        return
    old_content = path.read_text(encoding="utf-8")
    if old_content != new_content and old_content:
        backup_name = f"{path.name}.bak-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        backup_path = path.with_name(backup_name)
        if not what_if:
            shutil.copy2(path, backup_path)


def set_text_file(path: Path, content: str, what_if: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    backup_if_changed(path, content, what_if)
    if not what_if:
        path.write_text(content, encoding="utf-8")


def default_opencode_frontmatter(agent_root: Path) -> str:
    return "\n".join(
        [
            "---",
            f"description: 'Shared personal agent instructions generated from {agent_root}'",
            "label: human",
            "limit: 5000",
            "read_only: false",
            "---",
        ]
    )


def get_opencode_frontmatter(path: Path, agent_root: Path) -> str:
    if not path.exists():
        return default_opencode_frontmatter(agent_root)
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 2 or lines[0] != "---":
        return default_opencode_frontmatter(agent_root)
    for idx in range(1, len(lines)):
        if lines[idx] == "---":
            return "\n".join(lines[: idx + 1])
    return default_opencode_frontmatter(agent_root)


def main() -> int:
    args = parse_args()
    agent_root = Path(args.agent_root).expanduser().resolve()
    codex_agents_path = Path(args.codex_agents_path).expanduser()
    claude_path = Path(args.claude_path).expanduser()
    opencode_human_path = Path(args.opencode_human_path).expanduser()

    canonical_path = agent_root / "AGENTS.md"
    if not canonical_path.exists():
        raise FileNotFoundError(f"Canonical .agents AGENTS.md not found: {canonical_path}")
    canonical = canonical_path.read_text(encoding="utf-8").strip()

    generated_at = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %z")
    script_path = Path(__file__).resolve()

    codex_content = (
        f"<!-- Generated by {script_path} at {generated_at}. Edit {canonical_path} instead. -->\n\n"
        f"{canonical}\n\n"
        "## Codex Adapter\n\n"
        f"- Use Codex skills from ``{agent_root / 'skills'}`` when they are available in the session.\n"
        f"- Keep ``{Path.home() / '.codex' / 'skills' / '.system'}`` active for Codex built-in skill plumbing.\n"
        "- Keep public/imported Codex skill packs disabled unless explicitly restored.\n"
        "- Use ``tool_search`` for deferred app/MCP tool discovery when the task suggests a connected app may help.\n"
    )

    claude_content = (
        f"<!-- Generated by {script_path} at {generated_at}. Edit {canonical_path} instead. -->\n\n"
        f"{canonical}\n\n"
        "## Claude Adapter\n\n"
        "- Treat this as user memory guidance, not a hard policy layer.\n"
        "- Use Claude Code MCP tools, resources, and prompts when they directly match the task.\n"
        "- Use Claude Code skills when installed and relevant; otherwise follow the canonical `.agents` workflow.\n"
        "- Keep generated or imported public skill packs separate from personal skills.\n"
    )

    opencode_body = (
        f"Generated by ``{script_path}`` at {generated_at}.\n"
        f"Edit ``{canonical_path}`` instead.\n\n"
        f"{canonical}\n\n"
        "## OpenCode Adapter\n\n"
        f"- Use OpenCode MCP servers and commands from ``{Path.home() / '.config' / 'opencode' / 'opencode.jsonc'}`` when they directly match the task.\n"
        "- Prefer the configured utility-belt, GitHub, Firebase, Cloudflare, and Stripe MCP workflows when relevant.\n"
        f"- Use personal skills from ``{agent_root / 'skills'}`` through the installed OpenCode agent-skills capability when available.\n"
        "- Keep public/imported skill packs separate from personal skills.\n"
    )
    opencode_content = f"{get_opencode_frontmatter(opencode_human_path, agent_root).rstrip()}\n\n{opencode_body.rstrip()}\n"

    adapter_root = agent_root / "adapters"
    outputs = [
        (adapter_root / "codex" / "AGENTS.md", codex_content.rstrip() + "\n"),
        (adapter_root / "claude" / "CLAUDE.md", claude_content.rstrip() + "\n"),
        (adapter_root / "opencode" / "human.md", opencode_content),
        (codex_agents_path, codex_content.rstrip() + "\n"),
        (claude_path, claude_content.rstrip() + "\n"),
        (opencode_human_path, opencode_content),
    ]

    for output_path, content in outputs:
        set_text_file(output_path, content, what_if=args.what_if)
        print(output_path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
